test
vkucher49/spring-book-store pull request #12
Opened 2023-12-12 19:08 UTC by vkucher49

2023-12-14 12:17 UTC, Sanderfuck requested changes

2023-12-14 12:17 UTC, Sanderfuck commented on src/main/java/mate/academy/dto/category/CategoryRequestDto.java
> +    private String description;
Valid description, is is possible empty fields?

2023-12-14 12:17 UTC, Sanderfuck commented on src/main/java/mate/academy/model/Book.java
> +    private Category category;
You have set of categories and category field?

2023-12-14 12:17 UTC, Sanderfuck commented on src/main/java/mate/academy/model/Category.java
> +    private List<Book> books;
Are you sure?

2023-12-14 12:17 UTC, Sanderfuck commented on src/main/java/mate/academy/model/Role.java
>          ROLE_USER, ROLE_ADMIN
Write enums in stack

2023-12-14 12:17 UTC, Sanderfuck commented on src/main/java/mate/academy/service/CategoryServiceImpl.java
> +        Category saveCategory = categoryRepository.save(category);
```suggestion
        Category savedCategory = categoryRepository.save(category);
```

2023-12-15 10:04 UTC, Rommelua commented on src/main/java/mate/academy/controller/CategoryController.java
> +    public List<BookDtoWithoutCategoryIds> getBooksByCategoryId(@PathVariable Long id) {
![image](https://github.com/vkucher49/spring-book-store/assets/20326858/02545163-ba30-4286-994c-a12788f7fb6d)

2023-12-15 12:34 UTC, merged